[project]
name = "scheduleconverter"
version = "0.1.0"
description = "Converts university timetable to an importable calendar file."
authors = [{name = "Xavi", email = "xavisimpson04@gmail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icalendar>=5.0.13",
]
