[project]
name = "schedule-exporter"
version = "0.1.0"
description = "Converts university timetable to an importable calendar file."
authors = [{name = "Xavi", email = "xavisimpson04@gmail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icalendar>=5.0.13",
]

[project.scripts]
schedule-exporter = "schedule_exporter.converter:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["schedule_exporter"]
